version: '2.1'

services:
  db-node:
    build:
      context: mariadb
      dockerfile: Dockerfile
    container_name: db-node
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: service_db
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
      --init-file /data/application/init.sql
      --character-set-server=utf8mb4
    networks:
      - arch-network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mariadb --user=stud --password=stud --execute \"SHOW DATABASES;\""
      interval: 15s
      timeout: 1s
      retries: 5
    volumes:
      - db-node-data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql

  user_service:
    build:
      context: user_service
      dockerfile: Dockerfile
    container_name: user_service
    environment:
      - DB_HOST=db-node
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=service_db
    ports:
      - 8081:8081
    healthcheck:
      test: curl -sS http://localhost:8081/ || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
    networks:
      - arch-network
    depends_on:
      db-node:
        condition: service_healthy
        
  services_service:
    build:
      context: services_service
      dockerfile: Dockerfile
    container_name: services_service
    environment:
      - DB_HOST=db-node
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=service_db
    ports:
      - 8082:8082
    healthcheck:
      test: curl -sS http://localhost:8082/ || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
    networks:
      - arch-network
    depends_on:
      db-node:
        condition: service_healthy
      user_service:
        condition: service_healthy

  order_service:
    build:
      context: order_service
      dockerfile: Dockerfile
    container_name: order_service
    environment:
      - DB_HOST=db-node
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=service_db
    ports:
      - 8083:8083
    healthcheck:
      test: curl -sS http://localhost:8083/ || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
    networks:
      - arch-network
    depends_on:
      db-node:
        condition: service_healthy
      user_service:
        condition: service_healthy
      services_service:
        condition: service_healthy

  chat_service:
    build:
      context: chat_service
      dockerfile: Dockerfile
    container_name: chat_service
    environment:
      - DB_HOST=db-node
      - DB_PORT=3306
      - DB_LOGIN=stud
      - DB_PASSWORD=stud
      - DB_DATABASE=service_db
    ports:
      - 8084:8084
    healthcheck:
      test: curl -sS http://localhost:8084/ || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
    networks:
      - arch-network
    depends_on:
      db-node:
        condition: service_healthy
      user_service:
        condition: service_healthy
      order_service:
        condition: service_healthy
volumes:
  db-node-data:

networks:
  arch-network:
    driver: "bridge"
    external: false